In [ ]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[6, 2, 1],
       [7, 0, 7],
       [6, 0, 7]])

In [ ]:
np.random.randn(30,30).mean()

np.float64(-0.0021762290530103574)

In [ ]:
np.mean
std
var
np.median

In [ ]:
np.std(data)

np.float64(2.9814239699997196)

In [ ]:
np.std(data)

np.float64(8.88888888888889)

In [ ]:
np.mean(data)

np.float64(4.0)

In [ ]:
np.median(data)

np.float64(6.0)

In [ ]:
data=np.random.randint(0,100,10)
data

array([84, 44, 42, 46, 50, 22, 74,  0,  7, 37])

In [ ]:
data.min(),data.max()

(np.int64(0), np.int64(84))

In [ ]:
range=data.max()-data.min()
range

np.int64(84)

In [ ]:
import numpy as np
data=np.random.randint(0,5,(3,3))
data

array([[3, 4, 0],
       [4, 3, 0],
       [1, 2, 1]])

In [ ]:
data.sum(axis=0)

array([8, 9, 1])

In [ ]:
data=np.random.randint(0,10,(3,3))
data

array([[2, 6, 1],
       [4, 7, 1],
       [1, 9, 4]])

In [ ]:
data.max(axis=0)

array([4, 9, 4])

In [ ]:
data.min(axis=1)

array([1, 1, 1])

In [ ]:
data

array([[2, 6, 1],
       [4, 7, 1],
       [1, 9, 4]])

In [ ]:
data[0:2,0:2].max()

np.int64(7)

In [ ]:
data=np.random.randint(0,10,10)
data

array([9, 4, 1, 5, 6, 4, 9, 9, 2, 2])

In [ ]:
data.min()

np.int64(1)

In [ ]:
data.argmin()

np.int64(2)

In [ ]:
data=np.random.randint(0,100,(3,3))
data.argmin(axis=1)

array([2, 0, 0])

In [ ]:
data

array([[67, 95, 54],
       [29, 50, 67],
       [31, 34, 58]])

In [ ]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
[Store ID, Sales, Customers, Inventory, Returns]

In [ ]:
retail_data[:,1].sum()

np.int64(335000)

In [ ]:
retail_data[:,3].argmax()+1

np.int64(9)

In [ ]:
retail_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [ ]:
sales/customer
sales/transaction : basket value
sales/units: basket size

In [ ]:
[Store ID, Sales, Customers, Inventory, Returns]

In [ ]:
(retail_data[:,1]/retail_data[:,2]).argmax()+1

np.int64(1)

In [ ]:
retail_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [ ]:
[Store ID, Sales, Customers, Inventory, Returns]

In [ ]:
# Retail Data – Business Questions (for `retail_data`)

**Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis
1. What is the **total revenue** generated across all stores?
2. Which store recorded the **highest sales**?
3. Which store recorded the **lowest sales**?
4. What is the **average daily sales** per store?
5. How many stores achieved sales **above ₹35,000**?

## Customer Insights
6. Which store had the **highest customer footfall**?
7. What is the **average number of customers** per store?
8. How many stores have **more than 450 customers**?
9. Which store has the **lowest customer count**?
10. Is there any store where **high sales do not correspond to high customers**?

## Inventory & Returns Analysis
11. What is the **total inventory** across all stores?
12. Which store has the **highest inventory stock**?
13. How many stores have **inventory less than 1300 units**?
14. Which store has the **highest return rate** (returns ÷ inventory)?
15. Which stores have **returns greater than 15 units**?

## Sales & Customer Correlation
16. Is there a **positive correlation** between sales and customers?
17. Which store has **high customer visits but low sales**?
18. Which store has **low customers but high sales**?
19. How many stores have **sales per customer above ₹90**?
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

## Profitability & Growth
21. If profit margin is **20% of sales**, what is the **profit per store**?
22. Which store has the **highest profit**?
23. Which store has the **lowest profit**?
24. If sales increase by **10% next month**, what are the **new sales figures**?
25. How will **total profit** change with the 10% sales increase?

## Operational Strategy
26. Which stores need **inventory restocking** based on sales and current stock?
27. Which stores show **high returns percentage** and might require **quality checks**?
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
29. Which store is the **worst performer overall**?
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?


In [ ]:
data=np.random.randint(0,10,3)
x=20

In [ ]:
data+x

array([28, 22, 26])

In [ ]:
data

array([8, 2, 6])

In [ ]:
x=np.random.randint(0,10,(3,1))
y=np.random.randint(0,10,(1,3))
x+y

array([[13, 18, 10],
       [13, 18, 10],
       [12, 17,  9]])

In [ ]:
x

array([[9],
       [9],
       [8]])

In [ ]:
y

array([[4, 9, 1]])

In [ ]:
x=np.random.randint(0,10,(3,1))
y=np.random.randint(0,10,(1,3))

In [ ]:
x

array([[0],
       [2],
       [7]])

In [ ]:
y

array([[1, 7, 0]])